spring.application.name=app
server.port=8181

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html
# /api-docs endpoint custom path
springdoc.api-docs.path=/api-docs

# MySQL
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_HOST_PORT:3333}/${MYSQL_DATABASE:app-db}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${MYSQL_USER:user}
spring.datasource.password=${MYSQL_PASSWORD:user}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

## upload file directory
#file.upload-dir=

spring.servlet.multipart.max-file-size=1MB
spring.servlet.multipart.max-request-size=1MB

spring.jackson.time-zone=GMT+8

# JWT
jwt.secret=Unggea6AGald3M8ei0AAGEH9ou5STLCioqTbMNNn1gttf0lB650oGbEPSgMrtAhlsyQHsL73nvvL70gA5EiIwss9jgO1fizQTUMKWlo7e1KmW4sBE31qGngCuroYwEknwgBrflKp2hXRtMdUpdVDXw5erMiB7ShosgoP555Lhj1SxV5ZIbRd594ySme5ugV94EkATqqQ1vBQQ8aqh0AEQg4IXzcZLNcevUNkj263MenGFPm4nXySUECtfhGKqWFq
jwt.expiration-ms=86400000
jwt.issuer=demo-app

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

## OTel
#management.otlp.metrics.export.url=http://localhost:4318/v1/metrics
#management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4317
#management.opentelemetry.tracing.export.otlp.transport=grpc
#management.opentelemetry.logging.export.otlp.endpoint=http://localhost:4317
#management.opentelemetry.logging.export.otlp.transport=grpc
#management.tracing.sampling.probability=1.0
